baseURL: https://options.nix-darwin.uz/
languageCode: en-us
title: Xinux Nix Darwin - Option Search
theme: extranix-options-search

params:
  release_current_stable: nix-darwin-25.11
  releases:
    - name: unstable
      value: master
    - name: 24.11 (stable)
      value: nix-darwin-24.11
    - name: 25.05 (stable)
      value: nix-darwin-25.05
    - name: 25.11 (stable)
      value: nix-darwin-25.11

  release_switch_title: Nix Darwin Release

  custom_head_scripts: ""
  custom_header_tags: <div id="eadiv" data-ea-publisher="extranixcom" data-ea-type="text"></div>

  footer_credits_line: |
    Powered by <a href="https://xinux.uz/">Xinux</a> |
    <a href="https://github.com/xinux-org/nix-darwin-options?tab=readme-ov-file#credits--thanks">Credits</a> |
    <a href="https://nix-darwin.uz/">Xinux Nix Darwin Documentation</a>

  footer_copyright_line: |
    Made with ❤️ by <a href="https://github.com/mipmip">Pim Snel</a>, supported by <a href="https://github.com/orzklv">Orzklv</a> - © 2025

  logo: images/xinux-nix-darwin-options.png

  github:
    repo: nix-darwin-options
    user: xinux-org
    show_count: true
    show_text: true

  main_menu:
    - name: Nix&nbsp;Darwin&nbsp;Documentation
      url: https://nix-darwin.uz/
      icon_class: fa fa-book

    - name: Source
      url: https://github.com/xinux-org/nix-darwin-options
      icon_class: fa fa-github

markup:
  goldmark:
    renderer:
      unsafe: true
